TTLocalizer: Running in language: English
OTPLocalizer: Running in language: English
Preloading suits...
Preloading Toon heads...
Preloading avatars...
{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x14FAB7D8>}
__handleAvatarChooserDone: 100000010, 'Poodletooth', ('mss', 'ss', 'l', 'm', (0.79, 0.17, 0.17, 1.0), (0.47, 0.44, 0.44, 1.0), (0.78, 0.17, 0.17, 1.0), (0.12, 0.11, 0.51, 1.0), 104, 27, 91, 27, 4, 1), 1
entered wait for zone redirect
entered wait for set zone response - 2
Reading DNA file... phase_4/dna/storage.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_4/dna/storage_TT.pdna
Reading DNA file... phase_4/dna/storage_TT_sz.pdna
Reading DNA file... phase_4/dna/toontown_central_sz.pdna
gardenPage Unloading
{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x14FAB7D8>}
Exception occurred while processing Func-hide-7 of Sequence-8:
Sequence-8:
  0.000 Sequence-8 {
  0.000   Wait dur 0.1
  0.100   Wait dur 6
  6.100   LerpColorScaleInterval-6: color_scale to 1 1 1 0 dur 0.5
  6.600   *Func-hide-7
  6.600 }

Traceback (most recent call last):
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 1829, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 94, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 117, in __doPythonCallbacks
    ival.privPostEvent()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 519, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 495, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.10.0\direct\interval\Interval.py", line 206, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.10.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
AssertionError: !is_empty() at line 2271 of c:\users\john\desktop\panda3d-master\built\include\nodePath.I
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 34, in run
    taskMgr.run()
  File "C:\Panda3D-1.10.0\direct\task\Task.py", line 508, in run
    self.step()
  File "C:\Panda3D-1.10.0\direct\task\Task.py", line 465, in step
    self.mgr.poll()
  File "C:\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 1829, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 94, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\IntervalManager.py", line 117, in __doPythonCallbacks
    ival.privPostEvent()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 519, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.10.0\direct\interval\MetaInterval.py", line 495, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.10.0\direct\interval\Interval.py", line 206, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.10.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
AssertionError: !is_empty() at line 2271 of c:\users\john\desktop\panda3d-master\built\include\nodePath.I
